// Core domain types shared across providers, the pipeline engine, API routes and the UI.

export type Sector = "cafe" | "restaurant" | "gym";

export const SECTORS: { value: Sector; label: string }[] = [
  { value: "cafe", label: "Cafe" },
  { value: "restaurant", label: "Restaurant" },
  { value: "gym", label: "Gym / Fitness studio" }
];

export interface SearchQuery {
  country: string;
  city: string;
  sector: Sector;
}

/** One of the 5 candidate businesses shown after a search. */
export interface BusinessSummary {
  id: string;
  name: string;
  sector: Sector;
  country: string;
  city: string;
  address: string;
  phone: string;
  website: string | null;
  instagramHandle: string;
  rating: number; // 0-5
  reviewCount: number;
  priceLevel: 1 | 2 | 3 | 4;
  tags: string[];
  shortDescription: string;
  /** 0-100, how well it matches the searched sector/locale — used to rank the top 5. */
  matchScore: number;
}

/** A single photo pulled from the business's Instagram (or generated by the mock provider). */
export interface BrandAsset {
  id: string;
  kind: "profile" | "post";
  caption: string;
  /** data: URI — self-contained so the app has zero external image dependencies. */
  url: string;
  dominantColor: string; // hex
  likeCount: number;
}

export type StageKey =
  | "intake"
  | "research"
  | "local_context"
  | "brand_assets"
  | "content_strategy"
  | "copywriting"
  | "template_selection"
  | "page_assembly"
  | "seo_metadata"
  | "publish";

export type StageStatus = "pending" | "running" | "done" | "error";

export interface StageState {
  key: StageKey;
  title: string;
  status: StageStatus;
  detail: string | null;
  startedAt: string | null;
  finishedAt: string | null;
  logs: string[];
}

export interface ResearchNotes {
  category: string;
  openingHours: Record<string, string>;
  priceRange: string;
  specialties: string[];
  competitorNames: string[];
  neighborhoodSummary: string;
  sentimentSummary: string;
}

export interface ContentStrategy {
  sections: string[];
  primaryCallToAction: string;
  toneOfVoice: string;
}

export interface CopyContent {
  headline: string;
  subheadline: string;
  aboutParagraph: string;
  services: { title: string; description: string }[];
  testimonials: { author: string; quote: string }[];
  ctaText: string;
}

export interface SeoMeta {
  title: string;
  description: string;
  keywords: string[];
  jsonLd: Record<string, unknown>;
}

export type JobStatus = "queued" | "running" | "completed" | "failed";

export interface GeneratedSite {
  templateId: string;
  palette: { primary: string; secondary: string; text: string };
  /** Virtual file system for the generated static demo site: path -> file contents. */
  files: Record<string, string>;
  entryPoint: string; // e.g. "index.html"
}

export interface Job {
  id: string;
  business: BusinessSummary;
  status: JobStatus;
  createdAt: string;
  updatedAt: string;
  stages: StageState[];
  research: ResearchNotes | null;
  brandAssets: BrandAsset[];
  contentStrategy: ContentStrategy | null;
  copy: CopyContent | null;
  seo: SeoMeta | null;
  site: GeneratedSite | null;
  error: string | null;
}
